name: Go1.15

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:
    name: Test Go1.15
    runs-on: macos-10.15
    steps:
    
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.2
      with:
        node-version: 10.0.0
  
    - name: Set up Go 1.15
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
  
    - name: Install GopherJS
      run: |
        go version
        go get -v github.com/goplusjs/gopherjs
        cd $HOME/go/src/github.com/goplusjs/gopherjs
        npm install # Install our (dev) dependencies from package.json.
        cd node-syscall && ../node_modules/node-gyp/bin/node-gyp.js rebuild rebuild && mkdir -p ~/.node_libraries && cp build/Release/syscall.node ~/.node_libraries/syscall.node
  
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Build
      run: go build -v .

    - name: Go Test
      run: go test -v .
      
    - name: GopherJS Test
      run: gopherjs test -v
